[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.106.0"

[[redirects]]
  from = "https://docs.netlify.com/*"
  to = "https://bison.hudocs.com/:splat"
  status = 301
  force = true